languageCode: "en-us"
title: "dependencies.io"
baseURL: "https://www.dependencies.io/"
theme: "dropseed-hugo-theme"
PygmentsCodeFences: true
pygmentsstyle: monokai

menu:
  navbar:
    - Name: "Examples"
      Identifier: "examples"
      URL: "/examples/"
      weight: -100
    - Name: "Features"
      Identifier: "features"
      URL: "/features/"
      weight: -95
    - Name: "How It Works"
      Identifier: "how-it-works"
      URL: "/how-it-works/"
      weight: -95
    - Name: "Pricing"
      Identifier: "pricing"
      URL: "/pricing/"
      weight: -90
    - Name: "Contact"
      Identifier: "contact"
      URL: "/contact/"
      weight: -80
    - Name: "Docs"
      Identifier: "docs"
      URL: "/docs/"
      weight: -0

params:
  navbar_classes: "navbar-light"
  navbar_brand_text: "dependencies.io"
  navbar_logo: "dependencies-io-logo_shaded_60px.png"
  footer_logo: "dependencies-io-logo_light_150p.png"
  app_login_url: "https://app.dependencies.io/"
